paths:
  /auth:
    post:
      summary: Autentica um usuário e retorna um token JWT
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "ricardo@gmail.com"
                password:
                  type: string
                  example: "teste"
      responses:
        200:
          description: Token JWT retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        400:
          description: Dados inválidos
        401:
          description: Credenciais inválidas
        404:
          description: Usuário não encontrado
        500:
          description: Erro interno do servidor

  /user:
    post:
      summary: Cadastra um novo usuário
      tags: [Create User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Pedro Henrique Venâncio"
                email:
                  type: string
                  example: "phvenancio@gmail.com"
                password:
                  type: string
                  example: "DSM@a8bf4d"
      responses:
        201:
          description: Usuário cadastrado com sucesso
        500:
          description: Erro interno do servidor

  /times:
    get:
      summary: Retorna a lista de todos os times cadastrados
      tags: [Games]
      security:
        - bearerAuth: [] 
      responses:
        200:
          description: Lista de times
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "6782b9b16d6ea34ace5bd199"
                    nome:
                      type: string
                      example: "Corinthians"
                    pais:
                      type: string
                      example: "Brasil"
                    campeonato:
                      type: string
                      example: "Brasileirão"
                    estadio:
                      type: string
                      example: "Neo Química Arena"
                    tecnico: 
                      type: string
                      example: "Ramon Diaz"
                    titulares: 
                      type: array
                      items:
                        type: object
                        properties: 
                          nome: 
                            type: string,
                            example: "Rodrigo Garro"
                          numero: 
                            type: number
                            example: 8
        500:
          description: Erro interno do servidor

  /times:
    post:
      summary: Cadastra um novo time
      tags: [Games]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                      type: string
                      example: "Corinthians"
                    pais:
                      type: string
                      example: "Brasil"
                    campeonato:
                      type: string
                      example: "Brasileirão"
                    estadio:
                      type: string
                      example: "Neo Química Arena"
                    tecnico: 
                      type: string
                      example: "Ramon Diaz"
                    titulares: 
                      type: array
                      items:
                        type: object
                        properties: 
                          nome: 
                            type: string,
                            example: "Rodrigo Garro"
                          numero: 
                            type: number
                            example: 8
  /game/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: ID do jogo a ser manipulado
    delete:
      summary: Deleta um jogo pelo ID
      tags: [Games]
      security:
        - bearerAuth: []
      responses:
        204:
          description: Jogo deletado com sucesso
        400:
          description: Dados inválidos
        500:
          description: Erro interno do servidor
    put:
      summary: Altera um jogo pelo ID
      tags: [Games]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "CS-GO"
                platform:
                  type: string
                  example: "PC (Windows)"
                year:
                  type: integer
                  example: 2012
                price:
                  type: integer
                  example: 0
      responses:
        200:
          description: Jogo atualizado com sucesso
        400:
          description: Dados inválidos
        500:
          description: Erro interno do servidor

    get:
      summary: Retorna um jogo específico pelo ID
      tags: [Games]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Jogo encontrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "6782b9b16d6ea34ace5bd199"
                  title:
                    type: string
                    example: "CS-GO"
                  platform:
                    type: string
                    example: "PC (Windows)"
                  year:
                    type: integer
                    example: 2012
                  price:
                    type: integer
                    example: 0
        400:
          description: Dados inválidos
        500:
          description: Erro interno do servidor