/times:
  get:
    summary: Retorna a lista de todos os times cadastrados
    tags: [Listagem de todos os Times]
    security:
      - bearerAuth: []
    responses:
      200:
        description: Lista com todos os times
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: string
                    example: "6782b9b16d6ea34ace5bd199"
                  nome:
                    type: string
                    example: "Corinthians"
                  descricao:
                    type: string
                    example: "O Corinthians é um dos maiores e mais populares clubes de futebol do Brasil, fundado em 1º de setembro de 1910, em São Paulo. Conhecido como 'Timão', tem uma torcida apaixonada e história rica em conquistas, incluindo títulos do Campeonato Brasileiro, Libertadores da América e Mundial de Clubes da FIFA. O clube manda seus jogos na Neo Química Arena e é símbolo de garra, tradição e representatividade no futebol brasileiro."
                  pais:
                    type: string
                    example: "Brasil"
                  campeonato:
                    type: string
                    example: "Brasileirão"
                  estadio:
                    type: string
                    example: "Neo Química Arena"
                  tecnico:
                    type: array
                    items:
                      type: object
                      properties:
                        fotoTecnico:
                          type: string
                          example: "ramondiaz.png"
                        nomeTecnico:
                          type: string
                          example: "Ramon Diaz"
                        camisa:
                          type: array
                          items:
                            type: object
                            properties:
                              camisaGoleiro:
                                type: string
                                example: "hugoSouza.png"
                              camisaLinha:
                                type: string
                                example: "garro.png"
                  titulares:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                          example: "Rodrigo Garro"
                        numero:
                          type: number
                          example: 8
      500:
        description: Erro interno do servidor

  post:
    summary: Cadastra um novo time
    tags: [Cadastro de Time]
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              nome:
                type: string
                example: "Corinthians"
              descricao:
                type: string
                example: "O Corinthians é um dos maiores e mais populares clubes de futebol do Brasil, fundado em 1º de setembro de 1910, em São Paulo. Conhecido como 'Timão', tem uma torcida apaixonada e história rica em conquistas, incluindo títulos do Campeonato Brasileiro, Libertadores da América e Mundial de Clubes da FIFA. O clube manda seus jogos na Neo Química Arena e é símbolo de garra, tradição e representatividade no futebol brasileiro."
              pais:
                type: string
                example: "Brasil"
              campeonato:
                type: string
                example: "Brasileirão"
              estadio:
                type: string
                example: "Neo Química Arena"
              tecnico:
                type: array
                items:
                  type: object
                  properties:
                    fotoTecnico:
                      type: string
                      example: "ramondiaz.png"
                    nomeTecnico:
                      type: string
                      example: "Ramon Diaz"
                    camisa:
                      type: array
                      items:
                        type: object
                        properties:
                          camisaGoleiro:
                            type: string
                            example: "hugoSouza.png"
                          camisaLinha:
                            type: string
                            example: "garro.png"
              titulares:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                      example: "Rodrigo Garro"
                    numero:
                      type: number
                      example: 8

/times/{id}:
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: O ID do time a ser manipulado

  delete:
    summary: Apaga um time com base no seu ID
    tags: [Exclusão de time]
    security:
      - bearerAuth: []
    responses:
      204:
        description: Time excluído com sucesso
      400:
        description: Dados inválidos
      500:
        description: Erro interno do servidor

  put:
    summary: Altera um time com base no seu ID
    tags: [Alteração de Time]
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              nome:
                type: string
                example: "Corinthians"
              descricao:
                type: string
                example: "O Corinthians é um dos maiores e mais populares clubes de futebol do Brasil, fundado em 1º de setembro de 1910, em São Paulo. Conhecido como 'Timão', tem uma torcida apaixonada e história rica em conquistas, incluindo títulos do Campeonato Brasileiro, Libertadores da América e Mundial de Clubes da FIFA. O clube manda seus jogos na Neo Química Arena e é símbolo de garra, tradição e representatividade no futebol brasileiro."
              pais:
                type: string
                example: "Brasil"
              campeonato:
                type: string
                example: "Brasileirão"
              estadio:
                type: string
                example: "Neo Química Arena"
              tecnico:
                type: array
                items:
                  type: object
                  properties:
                    fotoTecnico:
                      type: string
                      example: "ramondiaz.png"
                    nomeTecnico:
                      type: string
                      example: "Ramon Diaz"
                    camisa:
                      type: array
                      items:
                        type: object
                        properties:
                          camisaGoleiro:
                            type: string
                            example: "hugoSouza.png"
                          camisaLinha:
                            type: string
                            example: "garro.png"
              titulares:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                      example: "Rodrigo Garro"
                    numero:
                      type: number
                      example: 8
    responses:
      200:
        description: Time alterado com sucesso
      400:
        description: Dados inválidos
      500:
        description: Erro interno do servidor

  get:
    summary: Retorna um time específico com base no seu ID
    tags: [Listagem de um Time]
    security:
      - bearerAuth: []
    responses:
      200:
        description: Time encontrado com sucesso
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                  example: "YVdgqn2rkj3HfJN9NbV1krru"
                nome:
                  type: string
                  example: "Barcelona"
                pais:
                  type: string
                  example: "Espanha"
                campeonato:
                  type: string
                  example: "La liga"
                estadio:
                  type: string
                  example: "Estádio Olímpico Lluís Companys"
                tecnico:
                  type: string
                  example: "Hansi Flick"
                titulares:
                  type: array
                  items:
                    type: object
                    properties:
                      nome:
                        type: string
                        example: "Raphinha"
                      numero:
                        type: number
                        example: 11
      400:
        description: Dados inválidos
      500:
        description: Erro interno do servidor
